pipeline {
    agent any
    
environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
}
stages {
    stage('building frontend') {
        steps {
            sh 'docker build -t shravaniii/lms-frontend .'
        }
    }
    stage('docker login'){
        steps{
            sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
        }
    }
    stage('pushing to dockerhub') {
        steps {
            sh 'docker push shravaniii/lms-frontend'
        }
    }
    stage('removing old dockerimage') {
        steps {
            sh 'docker rmi -f shravaniii/lms-frontend'
        }
    }
     stage('runing docker container') {
        steps {
            sh 'docker container run -dt --name lmsfn --network lmsnetwork -p 80:80 shravaniii/lms-frontend'
        }
     }
   }
}
