apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080  # External port for accessing the backend
      targetPort: 8080  # Port on which the backend is running in the container
  type: ClusterIP
