apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-backend
  template:
    metadata:
      labels:
        app: lms-backend
    spec:
      containers:
        - name: lms-backend
          image: shravaniii/mini-be
          envFrom:
            - name: MYSQL_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL-ROOT-USER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL-ROOT-PASSWORD
            - configMapRef:
                name: lms-config
          ports:
            - containerPort: 8080
