apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shravaniii/java-fe
          env:
            - name: BACKEND_HOST
              value: "backend-service"
            - name: BACKEND_PORT
              value: "8080"
          ports:
            - containerPort: 80  # Adjust the port based on your frontend application
