apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # External port for accessing the frontend
      targetPort: 80  # Port on which the frontend is running in the container
  type: ClusterIP
