apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD  #setting root password of mysql
              valueFrom:
                secretKeyRef:
                  name: mysql-root-secret  #name of the secret
                  key: password  #'key' inside the Secret which contains required 'value'
          ports:
            - containerPort: 3306
          volumeMounts:   #mounting volume obtained from Persistant Volume Claim
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql    #this is the container on which the mounting will takes place
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
