apiVersion: v1 
kind: Secret 
metadata: 
  name: mysql-root-secret 
type: Opaque 
data: 
  mysql-root-password: BASE64_ENCODED_PASSWORD 




#encode password using below command
#echo -n 'your_password' | base64


#to create a user in database
apiVersion: v1 
kind: Secret 
metadata: 
  name: mysql-user
data: 
  username: db-user #[BASE64_ENCODED_PASSWORD]
  password: password #[BASE64_ENCODED_PASSWORD]
